on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run JMeter Tests
        uses: ./
        with:
          test-plan-path: './TestPlans/Consulta_CEP/consulta_de_cep.jmx'
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: resultGit.jtl

      name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ./TestPlans/Consulta_CEP/consulta_de_cep.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"